name: Deploy Client with Plugins to GitHub Pages

on:
  push:
    branches: [gun]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build project
        run: pnpm build
        
      # Fetch and integrate event plugin
      - name: Checkout event plugin
        uses: actions/checkout@v4
        with:
          repository: toplocs/event-plugin
          ref: event-plugin-p2p
          path: temp-plugin
          
      - name: Build event plugin
        run: |
          cd temp-plugin
          pnpm install
          pnpm build-only
          cd ..
          
      - name: Copy plugin to deployment
        run: |
          mkdir -p server/dist/views/plugins/event-plugin
          cp -r temp-plugin/dist/* server/dist/views/plugins/event-plugin/
          
      # Register plugin in index.html or via Gun
      - name: Register plugin
        run: |
          cat >> server/dist/views/plugin-registry.js << 'EOF'
          // Auto-register P2P Event Plugin
          if (window.gun) {
            window.gun.get('plugins').get('event-plugin-p2p').put({
              id: 'event-plugin-p2p',
              name: 'Events (P2P)',
              description: 'Pure P2P event management',
              url: '/plugins/event-plugin/assets/plugin.js',
              version: '1.0.0',
              author: 'Tribelike Community',
              category: 'social',
              enabled: true
            });
          }
          EOF
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./server/dist/views

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4